services:
  diamonbank-configserver:
    image: chamow01/diamonbank-config-server:latest
    mem_limit: 700m
    ports:
    - "8071:8071"
    networks:
      - diamonbank-network

  diamondbank-accounts:
    image: chamow01/diamonbank-accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - diamonbank-network
    depends_on:
      - diamonbank-configserver
    extends:
      file: deploy-area.yml
      service: deploy_area

  diamondbank-loans:
    image: chamow01/diamonbank-loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - diamonbank-network
    depends_on:
      - diamonbank-configserver
    extends:
      file: deploy-area.yml
      service: deploy_area

  diamondbank-cards:
    image: chamow01/diamonbank-cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - diamonbank-network
    depends_on:
      - diamonbank-configserver
    extends:
      file: deploy-area.yml
      service: deploy_area
networks:
  diamonbank-network:
