global:
  configMapName: diamonbank-configmap
  secretName: diamonbank-secret

  env:
    SPRING_ZIPKIN_BASEURL: "http://zipkin:9411/"
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin-service:9411/api/v2/spans"
    SPRING_PROFILES_ACTIVE: "dev"
    SPRING_CONFIG_IMPORT: "configserver:http://configserver-service:8081/"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver-service:8070/eureka/"
    #I18N_URL: "http://dci18n:8080/"
    SPRING_RABBITMQ_HOST: "rabbit_server"
    SPRING_RABBITMQ_QUEUE: "rabbit-queue-testing"
    SPRING_RABBITMQ_EXCHANGE: "rabbit-exchange-testing"
    SPRING_RABBITMQ_ROUTING: "rabbit-routing-testing"
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://my-release-keycloak:80/realms/diamon-bank/protocol/openid-connect/certs"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: "http://my-release-keycloak:80/realms/diamon-bank/protocol/openid-connect/token"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI: "http://my-release-keycloak:80/realms/diamon-bank/protocol/openid-connect/auth"
    SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_URI: "http://my-release-keycloak:80/realms/diamon-bank/protocol/openid-connect/userinfo"
  secret:
    KEY_CLOAK_CLIENT_ID: diamonbank-gateway-ui
    KEY_CLOAK_CLIENT_SECRET: 7FtQvG7bNiIXlTXACX9KBmC14zaPdDTx

configserver:
  enabled: true
eureka-server:
  enabled: true
accounts:
  enabled: true
loans:
  enabled: true
cards:
  enabled: true
apigw:
  enabled: true



