apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.deploymentName } }
  labels:
    app: { { .Values.deploymentLabel } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { .Values.deploymentLabel } }
  template:
    metadata:
      labels:
        app: { { .Values.deploymentLabel } }
    spec:
      containers:
        - name: { { .Values.deploymentLabel } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: { { .Values.containerPort } }
              protocol: TCP
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: { { .Values.global.configMapName } }
                  key: { { .Values.deploymentName } }
            { { - if .Values.custom.serverPort } }
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: { { .Values.global.configMapName } }
                  key: { { .Values.custom.serverPort } }
            { { - end } }
            { { - if .Values.zipkin_enabled } }
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: { { .Values.global.configMapName } }
                  key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: { { .Values.global.configMapName } }
                  key: ZIPKIN_SPRING_BASEURL
            { { - end } }
            { { - if .Values.profile_enabled } }
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: { { .Values.global.configMapName } }
                  key: SPRING_PROFILES_ACTIVE
            { { - end } }
            { { - if .Values.config_enabled } }
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: { { .Values.global.configMapName } }
                  key: SPRING_CONFIG_IMPORT
            { { - end } }
            { { - if .Values.eureka_enabled } }
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: { { .Values.global.configMapName } }
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            { { - end } }
