name: cards
targetPort: 9000

deployment:
  label: cards
  replicaCount: 1

containers:
  image:
    repository: chamow01/diamonbank-cards
    version: latest

service:
  type: ClusterIP
  port: 9000


services:
  SPRING_APPLICATION_NAME: cards
  zipkin_enabled: true
  config_enabled: true
  eureka_enabled: true
