version: "3"

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true
  docker-compose-up:
    cmds:
      - cd docker && docker compose up -d
    silent: true
  docker-compose-up-debug:
    cmds:      
      - cd docker && docker compose -f docker-compose.yml -f docker-compose-debug.yml up -d
    silent: true
  docker-compose-stop:
    cmds:
      - cd docker && docker compose stop
    silent: true
  docker-compose-down:
    cmds:
      - cd docker && docker compose down
    silent: true
  local-image-loans:
    cmds:
      - cd diamonbank-loans && docker build -t local/diamoncode-loans:SNAPSHOT .
    silent: true
  local-image-accounts:
    cmds:
      - cd diamonbank-accounts && mvn clean install && docker build -t local/diamoncode-accounts:SNAPSHOT .
    silent: true
  local-image-cards:
      cmds:
        - cd diamonbank-cards && mvn clean install && mvn spring-boot:build-image
      silent: true
  local-image-config-server:
    cmds:
      - cd diamonbank-config-server && mvn clean install && mvn spring-boot:build-image
    silent: true
  local-image-eureka-server:
      cmds:
        - cd diamonbank-eureka-server && mvn clean install && mvn spring-boot:build-image
      silent: true
  local-image-gateway:
    cmds:
      - cd diamonbank-apigateway && mvn clean install -DskipTests && mvn spring-boot:build-image
    silent: true

  
