version: "3"
includes:
  accounts:
    taskfile: ./diamonbank-accounts/Taskfile.yml
    dir: ./diamonbank-accounts
  eureka-server:
    taskfile: ./diamonbank-eureka-server/Taskfile.yml
    dir: ./diamonbank-eureka-server
  apigateway:
    taskfile: ./diamonbank-apigateway/Taskfile.yml
    dir: ./diamonbank-apigateway
tasks:
  docker-pull-images:
    dotenv: ['docker/.env_template']
    cmds:
      - docker pull $CONFIG_SERVER_IMAGE
      - docker pull $EUREKA_SERVER_IMAGE
      - docker pull $ACCOUNTS_IMAGE
      - docker pull $LOANS_IMAGE
      - docker pull $CARDS_IMAGE
      - docker pull $I18N_IMAGE
      - docker pull $APIGATEWAY_IMAGE
      - echo 'All images were downloaded!'
    silent: true
  docker-compose-up:
    cmds:
      - cd docker && docker compose up -d
    silent: true
  docker-compose-up-debug:
    cmds:      
      - cd docker && docker compose -f docker-compose.yml -f docker-compose-debug.yml up -d
    silent: true
  docker-compose-stop:
    cmds:
      - cd docker && docker compose stop
    silent: true
  docker-compose-down:
    cmds:
      - cd docker && docker compose down
    silent: true
  local-image-loans:
    cmds:
      - cd diamonbank-loans && docker build -t local/diamoncode-loans:SNAPSHOT .
    silent: true

  local-image-cards:
      cmds:
        - cd diamonbank-cards && mvn clean install && mvn spring-boot:build-image
      silent: true
  local-image-config-server:
    cmds:
      - cd diamonbank-config-server && mvn clean install && mvn spring-boot:build-image
    silent: true

  
