name: configserver
targetPort: 8081

deployment:
  label: configserver
  replicaCount: 1

containers:
  image:
    repository: chamow01/diamonbank-config-server
    version: latest

service:
  type: LoadBalancer
  port: 8081


services:
  SPRING_SERVER_PORT: 8081
  zipkin_enabled: true
  