apiVersion: v1
kind: ConfigMap
metadata:
  name: diamonbank-configmap
data:
  ZIPKIN_SPRING_BASEURL: "http://zipkin-service:9411/"
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_CONFIG_IMPORT: "configserver:http://configserver-service:8081/"
  CONFIG_SERVER_PORT: "8081"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver-service:8070/eureka/"
  I18N_URL: "http://dci18n:8080/"
  APIGW_SERVER_PORT: "8099"
  SPRING_RABBITMQ_HOST: "rabbit_server"
  SPRING_RABBITMQ_QUEUE: "rabbit-queue-testing"
  SPRING_RABBITMQ_EXCHANGE: "rabbit-exchange-testing"
  SPRING_RABBITMQ_ROUTING: "rabbit-routing-testing"
