services:
  deploy_area:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - diamonbank_ns
    environment:
      - SPRING_PROFILES_ACTIVE=${DEPLOY_ENVIRONMENT}
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8081/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
      - I18N_URL=http://dci18n:8080/
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411/
      - SPRING_RABBITMQ_HOST=rabbit_server
      - SPRING_RABBITMQ_PORT=5674
      - SPRING_RABBITMQ_USERNAME=username
      - SPRING_RABBITMQ_PASSWORD=password
      - SPRING_RABBITMQ_QUEUE=rabbit-queue-testing
      - SPRING_RABBITMQ_EXCHANGE=rabbit-exchange-testing
      - SPRING_RABBITMQ_ROUTING=rabbit-routing-testing
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI=http://keycloak_server:7080/realms/master/protocol/openid-connect/certs
