services:
  deploy_area:
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - diamonbank_ns
    environment:
      - SPRING_PROFILES_ACTIVE=${DEPLOY_ENVIRONMENT}
      - SPRING_CONFIG_IMPORT=configserver:http://configserver:8081/
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8070/eureka/
      - I18N_URL=http://dci18n:8080/
      - SPRING_ZIPKIN_BASEURL=http://zipkin:9411/
      - SPRING_RABBITMQ_HOST=rabbit_server
