version: "3.1"
services:
  configserver:
    image: ${CONFIG_SERVER_IMAGE}
    container_name: configserver
    mem_limit: 700m
    ports:
      - "8082:8081"
    networks:
      - diamonbank_ns
    environment:
      SERVER_PORT: 8081

  eurekaserver:
    image: ${EUREKA_SERVER_IMAGE}
    container_name: eurekaserver
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - diamonbank_ns
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 25s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8081/


  dci18n:
    image: ${I18N_IMAGE}
    container_name: dci18n
    ports:
      - "9100:8080"
    networks:
      - diamonbank_ns
    environment:
      - SPRING_DATASOURCE_URL=${I18N_DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 500M

  accounts:
    image: ${ACCOUNTS_IMAGE}
    container_name: accounts
    mem_limit: 700m
    depends_on:
      - configserver
      - eurekaserver
    extends:
      file: deploy-area.yml
      service: deploy_area
    ports:
      - "9082:9082"
      - "5005:5005"
    environment:
      - DEBUG_ENABLED=true
  #accounts1:
  #  image: ${ACCOUNTS_IMAGE}
  #  container_name: accounts1
  #  mem_limit: 700m
  #  depends_on:
      - configserver
      - eurekaserver
  #  extends:
      file: deploy-area.yml
      service: deploy_area
  #  ports:
  #    - "9087:9082"


  loans:
    image: ${LOANS_IMAGE}
    container_name: loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    depends_on:
      - configserver
      - eurekaserver
    extends:
      file: deploy-area.yml
      service: deploy_area

  cards:
    image: ${CARDS_IMAGE}
    container_name: cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    depends_on:
      - configserver
      - eurekaserver
    extends:
      file: deploy-area.yml
      service: deploy_area

networks:
  diamonbank_ns:
