version: "3.1"
services:
  configserver:
    image: ${CONFIG_SERVER_IMAGE}
    container_name: configserver
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - diamonbank-network

  eurekaserver:
    image: ${EUREKA_SERVER_IMAGE}
    container_name: eurekaserver
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - diamonbank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: ${ACCOUNTS_IMAGE}
    container_name: accounts
    mem_limit: 700m
    depends_on:
      - configserver
      - eurekaserver
    extends:
      file: deploy-area.yml
      service: deploy_area
    ports:
      - "8080:8080"
    networks:
      - diamonbank-network
  loans:
    image: ${LOANS_IMAGE}
    container_name: loans
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - diamonbank-network
    depends_on:
      - configserver
      - eurekaserver
    extends:
      file: deploy-area.yml
      service: deploy_area

  cards:
    image: ${CARDS_IMAGE}
    container_name: cards
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - diamonbank-network
    depends_on:
      - configserver
      - eurekaserver
    extends:
      file: deploy-area.yml
      service: deploy_area

  i18n:
    image: ${I18N_IMAGE}
    container_name: dc_i18n
    ports:
      - "9100:8080"
    healthcheck:
      test: curl  --fail http://localhost:8080/actuator/health || exit 1
    environment:
      - SPRING_DATASOURCE_URL=${I18N_DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USER}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    deploy:
      resources:
        limits:
          memory: 800M
        reservations:
          memory: 500M
networks:
  diamonbank-network:
