name: gatewayserver

deployment:
  label: gatewayserver-deployment
  replicaCount: 1
  image:
    repository: chamow01/diamonbank-apigateway
    version: latest
  containerPort: 8099

service:
  type: LoadBalancer
  port: 8099
  targetPort: 8099


services:
  SPRING_APPLICATION_NAME: gatewayserver
  SPRING_SERVER_PORT: 8099
  zipkin_enabled: true
  config_enabled: true
  eureka_enabled: true
    

