name: gatewayserver

deployment:
  label: gatewayserver-deployment
  replicaCount: 1
  image:
    repository: chamow01/diamonbank-apigateway
    version: latest
  containerPort: 8099

service:
  type: LoadBalancer
  port: 8099
  targetPort: 8099


configMap:
  name: diamonbank-configmap
  env:
    SPRING_SERVER_PORT: 8099
    SPRING_APPLICATION_NAME: gatewayserver
    MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin-service:9411/api/v2/spans
    ZIPKIN_SPRING_BASEURL: "http://zipkin-service:9411/"
    SPRING_PROFILES_ACTIVE: "prod"
    SPRING_CONFIG_IMPORT: "configserver:http://configserver-service:8081/"
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eurekaserver-service:8070/eureka/"
    

