name: gatewayserver
targetPort: 8099

deployment:
  label: gatewayserver
  replicaCount: 1

containers:
  image:
    repository: chamow01/diamonbank-apigateway
    version: latest

service:
  type: LoadBalancer
  port: 8099


services:
  SPRING_APPLICATION_NAME: gatewayserver
  SPRING_SERVER_PORT: 8099
  zipkin_enabled: true
  config_enabled: true
  eureka_enabled: true
    

