name: loans
targetPort: 8090

deployment:
  label: loans
  replicaCount: 1

containers:
  image:
    repository: chamow01/diamonbank-loans
    version: latest

service:
  type: LoadBalancer
  port: 8090


services:
  SPRING_APPLICATION_NAME: loans
  zipkin_enabled: true
  config_enabled: true
  eureka_enabled: true