version: "3"

vars:
  IMAGE_NAME: diamonbank-cards
  LOCAL_IMAGE: local/{{.IMAGE_NAME}}:SNAPSHOT
  DOCKER_HUB_IMAGE_VERSION: chamow01/{{.IMAGE_NAME}}:v1
  DOCKER_HUB_IMAGE_FINAL: chamow01/{{.IMAGE_NAME}}:latest

tasks:
  mvn-clean-install:
    cmds:
      - mvn clean install -Dmaven.test.skip=true
  local-image:
    cmds:
      - task: mvn-clean-install
      - mvn spring-boot:build-image -Dmy-image-name={{.LOCAL_IMAGE}} -Dmaven.test.skip=true
  docker-hub-image:
    cmds:
      - task: mvn-clean-install
      - mvn spring-boot:build-image -Dmy-image-name={{.DOCKER_HUB_IMAGE_VERSION}} -Dmaven.test.skip=true
      - docker tag {{.DOCKER_HUB_IMAGE_VERSION}} {{.DOCKER_HUB_IMAGE_FINAL}}
      - docker push {{.DOCKER_HUB_IMAGE_FINAL}}
