{{- define "common.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.global.configMapName }}"
data:
  SPRING_ZIPKIN_BASEURL: "{{ .Values.global.env.SPRING_ZIPKIN_BASEURL }}"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "{{ .Values.global.env.MANAGEMENT_ZIPKIN_TRACING_ENDPOINT }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.global.env.SPRING_PROFILES_ACTIVE }}"
  SPRING_CONFIG_IMPORT: "{{ .Values.global.env.SPRING_CONFIG_IMPORT }}"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "{{ .Values.global.env.EUREKA_CLIENT_SERVICEURL_DEFAULTZONE }}"
  I18N_URL: "{{ .Values.global.env.I18N_URL }}"
  SPRING_RABBITMQ_HOST: "{{ .Values.global.env.SPRING_RABBITMQ_HOST }}"
  SPRING_RABBITMQ_QUEUE: "{{ .Values.global.env.SPRING_RABBITMQ_QUEUE }}"
  SPRING_RABBITMQ_EXCHANGE: "{{ .Values.global.env.SPRING_RABBITMQ_EXCHANGE }}"
  SPRING_RABBITMQ_ROUTING: "{{ .Values.global.env.SPRING_RABBITMQ_ROUTING }}"
{{- end -}}
