{{- define "common.configmap" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: { { .Values.configMap.name } }
data:
  ZIPKIN_SPRING_BASEURL: { { .Values.configMap.env.ZIPKIN_SPRING_BASEURL } }
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: { { .Values.configMap.env.MANAGEMENT_ZIPKIN_TRACING_ENDPOINT } }
  SPRING_PROFILES_ACTIVE: { { .Values.configMap.env.SPRING_PROFILES_ACTIVE } }
  SPRING_CONFIG_IMPORT: { { .Values.configMap.env.CONFIG_SERVER_URL } }
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: { { .Values.configMap.env.EUREKA_SERVER_URL } }
  I18N_URL: { { .Values.configMap.env.I18N_URL } }
  SPRING_RABBITMQ_HOST: { { .Values.configMap.env.SPRING_RABBITMQ_HOST } }
  SPRING_RABBITMQ_QUEUE: { { .Values.configMap.env.SPRING_RABBITMQ_QUEUE } }
  SPRING_RABBITMQ_EXCHANGE: { { .Values.configMap.env.SPRING_RABBITMQ_EXCHANGE } }
  SPRING_RABBITMQ_ROUTING: { { .Values.configMap.env.SPRING_RABBITMQ_ROUTING } }
{{- end -}}
