{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}-deployment"
  labels:
    app: {{ .Values.deployment.label }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.label }}
    spec:
      containers:
      - name: "{{ .Values.name }}-container"
        image: "{{ .Values.containers.image.repository }}:{{ .Values.containers.image.version }}"
        ports:
        - containerPort: {{ .Values.targetPort }}
          protocol: TCP
        {{- if .Values.services}}
        env:
        {{- if .Values.services.SPRING_APPLICATION_NAME }}
        - name: SPRING_APPLICATION_NAME
          value: {{ .Values.services.SPRING_APPLICATION_NAME }}
        {{- end }}
        {{- if .Values.services.SPRING_SERVER_PORT }}
        - name: SERVER_PORT
          value: "{{ .Values.services.SPRING_SERVER_PORT }}"
        {{- end }}
        {{- if .Values.services.zipkin_enabled }}
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_ZIPKIN_BASEURL
        {{- end }}
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_PROFILES_ACTIVE
        {{- if .Values.services.config_enabled }}
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_CONFIG_IMPORT
        {{- end }}
        {{- if .Values.services.eureka_enabled }}
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        {{- end }}
        { { - if .Values.services.resourceserver_enabled }}
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
        {{ - end }}
        {{ - if .Values.services.keycloak_enabled }}
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_AUTHORIZATION_URI
        - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_URI
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DIAMONCODEBANK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.global.secretName }}
              key: KEY_CLOAK_CLIENT_ID
        - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_DIAMONCODEBANK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: { { .Values.global.secretName } }
              key: KEY_CLOAK_CLIENT_SECRET
        {{ - end }}
        {{- end }}
{{- end -}}
