{{- define "common.deployment" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.deployment.label }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}"
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
          protocol: TCP
        {{- if .Values.services}}
        env:
        {{- if .Values.services.SPRING_APPLICATION_NAME }}
        - name: SPRING_APPLICATION_NAME
          value: {{ .Values.services.SPRING_APPLICATION_NAME }}
        {{- end }}
        {{- if .Values.services.SPRING_SERVER_PORT }}
        - name: SERVER_PORT
          value: {{ .Values.services.SPRING_SERVER_PORT }}
        {{- end }}
        {{- if .Values.services.zipkin_enabled }}
        - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
        - name: SPRING_ZIPKIN_BASEURL
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_ZIPKIN_BASEURL
        {{- end }}
        {{- if .Values.services.config_enabled }}
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: SPRING_CONFIG_IMPORT
        {{- end }}
        {{- if .Values.services.eureka_enabled }}
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.global.configMapName }}
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        {{- end }}
        {{- end }}
{{- end -}}
