name: accounts
targetPort: 9082

deployment:
  label: accounts
  replicaCount: 1

containers:
  image:
    repository: chamow01/diamonbank-accounts
    version: latest

service:
  type: ClusterIP
  port: 9082


services:
  SPRING_APPLICATION_NAME: accounts
  zipkin_enabled: true
  config_enabled: true
  eureka_enabled: true
  