name: accounts

deployment:
  label: accounts-deployment
  replicaCount: 1
  image:
    repository: chamow01/diamonbank-accounts
    version: latest
  containerPort: 9082

service:
  type: LoadBalancer
  port: 9082
  targetPort: 9082


services:
  SPRING_APPLICATION_NAME: accounts
  zipkin_enabled: true
  config_enabled: true
  eureka_enabled: true
  