name: eurekaserver
targetPort: 8070

deployment:
  label: eurekaserver
  replicaCount: 1

containers:
  image:
    repository: chamow01/diamonbank-eureka-server
    version: latest

service:
  type: LoadBalancer
  port: 8070


services:
  zipkin_enabled: true
  config_enabled: true